openapi: 3.0.0
info:
  title: Book Management API
  description: A simple API for managing books with JWT authentication.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: password123
      responses:
        '201':
          description: User registered successfully
        '500':
          description: Internal server error

  /login:
    post:
      summary: Log in and get a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: JWT token returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsIn...
        '401':
          description: Invalid credentials
        '500':
          description: Internal server error

  /books:
    get:
      summary: Retrieve a list of all books
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: The Great Gatsby
                    author:
                      type: string
                      example: F. Scott Fitzgerald
                    published_date:
                      type: string
                      format: date
                      example: 1925-04-10
                    isbn:
                      type: string
                      example: 9780743273565
                    pages:
                      type: integer
                      example: 180
                    cover_url:
                      type: string
                      example: http://example.com/cover.jpg
                    language:
                      type: string
                      example: English
        '401':
          description: Unauthorized

    post:
      summary: Create a new book
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: The Great Gatsby
                author:
                  type: string
                  example: F. Scott Fitzgerald
                published_date:
                  type: string
                  format: date
                  example: 1925-04-10
                isbn:
                  type: string
                  example: 9780743273565
                pages:
                  type: integer
                  example: 180
                cover_url:
                  type: string
                  example: http://example.com/cover.jpg
                language:
                  type: string
                  example: English
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  title:
                    type: string
                    example: The Great Gatsby
                  author:
                    type: string
                    example: F. Scott Fitzgerald
                  published_date:
                    type: string
                    format: date
                    example: 1925-04-10
                  isbn:
                    type: string
                    example: 9780743273565
                  pages:
                    type: integer
                    example: 180
                  cover_url:
                    type: string
                    example: http://example.com/cover.jpg
                  language:
                    type: string
                    example: English
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /books/{id}:
    get:
      summary: Retrieve a single book by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Book details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  title:
                    type: string
                    example: The Great Gatsby
                  author:
                    type: string
                    example: F. Scott Fitzgerald
                  published_date:
                    type: string
                    format: date
                    example: 1925-04-10
                  isbn:
                    type: string
                    example: 9780743273565
                  pages:
                    type: integer
                    example: 180
                  cover_url:
                    type: string
                    example: http://example.com/cover.jpg
                  language:
                    type: string
                    example: English
        '404':
          description: Book not found
        '401':
          description: Unauthorized

    put:
      summary: Update an existing book
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: The Great Gatsby
                author:
                  type: string
                  example: F. Scott Fitzgerald
                published_date:
                  type: string
                  format: date
                  example: 1925-04-10
                isbn:
                  type: string
                  example: 9780743273565
                pages:
                  type: integer
                  example: 180
                cover_url:
                  type: string
                  example: http://example.com/cover.jpg
                language:
                  type: string
                  example: English
      responses:
        '200':
          description: Book updated successfully
        '404':
          description: Book not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    delete:
      summary: Delete a book
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Book deleted successfully
        '404':
          description: Book not found
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT